services:
  redis-cache:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - golang-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq-broker
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - golang-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    restart: on-failure
    environment:
      DB_HOST: "database-1.cbu2iguumukf.ap-southeast-2.rds.amazonaws.com"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "db_test"
      DB_SSLROOTCERT: "/app/global-bundle.pem"
    volumes:
      - ./global-bundle.pem:/app/global-bundle.pem
    ports:
      - "8080:8080"
    networks:
      - golang-network
    depends_on:
      redis-cache:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - golang-network
    depends_on:
      - api

networks:
  golang-network:
    driver: bridge